services:
  lingo-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: lingo-app-ctr

    environment:
      - WATCHPACK_POLLING=true
      - NODE_ENV=development

    volumes:
      - .:/app
      - /app/node_modules

    ports:
      - 3001:3000

    env_file:
      - .env.local

    command: npm run dev
